title: P4wnda
description: Cybersecurity. CTFs. Japan.
author: P4wnda
theme: null
markdown: kramdown
permalink: pretty

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true
  overthewire_bandit:
    output: true
    permalink: /overthewire/bandit/:title/
  overthewire_natas:
    output: true
    permalink: /overthewire/natas/:title/
  overthewire_leviathan:
    output: true
    permalink: /overthewire/leviathan/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: overthewire_bandit
    values:
      layout: post
      type: posts
  - scope:
      path: ""
      type: overthewire_natas
    values:
      layout: post
      type: posts
  - scope:
      path: ""
      type: overthewire_leviathan
    values:
      layout: post
      type: posts

exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
